model_args:
  pretrained_model_name_or_path: "Qwen/Qwen3-1.7B"
  attn_implementation: 'eager'
  torch_dtype: bfloat16
  output_attentions: True
tokenizer_args:
  pretrained_model_name_or_path: "Qwen/Qwen3-1.7B"
template_args:
  apply_chat_template: True
  system_prompt: You are a helpful assistant.
  system_prompt_with_special_tokens: "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n"
  user_start_tag: "<|im_start|>user\n"
  user_end_tag: "<|im_end|>\n"
  asst_start_tag: "<|im_start|>assistant\n"
  asst_end_tag: "<|im_end|>\n" 

  # user_start_tag: "Question: "
  # user_end_tag: "\n"
  # asst_start_tag: "Answer: "
  # asst_end_tag: "\n\n"