# @package _global_

defaults:
  - _self_
  - model: Llama-3.2-3B-Instruct
  - trainer: GradAscent
  - eval: tofu
  - paths: default
  - hydra: eval
  - experiment: null

model:
  model_args:
    pretrained_model_name_or_path: ""
    device_map: "cuda"
    attn_implementation: "eager"
    output_attentions: true

mode: eval
task_name: ???
seed: 0